# Generated by Django 5.2.11 on 2026-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_by_principal", models.CharField(max_length=255)),
                ("requested_role", models.CharField(max_length=128)),
                ("justification", models.TextField(default="")),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "reviewed_by_principal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_principal", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("active_flag", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_principal", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=128)),
                (
                    "granted_by_principal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_principal", "role"),
                        name="uq_role_assignment_principal_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_principal", models.CharField(max_length=255)),
                ("terms_version", models.CharField(max_length=64)),
                (
                    "ip_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_principal", "terms_version"),
                        name="uq_terms_acceptance_principal_version",
                    )
                ],
            },
        ),
    ]
