# Generated by Django 5.2.11 on 2026-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_principal", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=128)),
                (
                    "granted_by_principal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_principal", "role"),
                        name="uq_group_role_assignment_group_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScopeGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_principal", models.CharField(max_length=255)),
                ("org_id", models.CharField(max_length=128)),
                ("scope_level", models.CharField(max_length=64)),
                (
                    "granted_by_principal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_principal", "org_id", "scope_level"),
                        name="uq_scope_grant_principal_org_scope",
                    )
                ],
            },
        ),
    ]
