from __future__ import annotations

import os
from collections.abc import Iterable

from vendor_catalog_app.core.util import as_bool, as_float, as_int

# Canonical TVENDOR runtime configuration keys.
TVENDOR_ENV = "TVENDOR_ENV"
TVENDOR_FQ_SCHEMA = "TVENDOR_FQ_SCHEMA"
TVENDOR_CATALOG = "TVENDOR_CATALOG"
TVENDOR_SCHEMA = "TVENDOR_SCHEMA"
TVENDOR_ALLOWED_WRITE_VERBS = "TVENDOR_ALLOWED_WRITE_VERBS"
TVENDOR_USE_LOCAL_DB = "TVENDOR_USE_LOCAL_DB"
TVENDOR_LOCAL_DB_PATH = "TVENDOR_LOCAL_DB_PATH"
TVENDOR_LOCKED_MODE = "TVENDOR_LOCKED_MODE"
TVENDOR_ENFORCE_PROD_SQL_POLICY = "TVENDOR_ENFORCE_PROD_SQL_POLICY"
TVENDOR_SCHEMA_BOOTSTRAP_SQL = "TVENDOR_SCHEMA_BOOTSTRAP_SQL"
TVENDOR_SQL_PRELOAD_ON_STARTUP = "TVENDOR_SQL_PRELOAD_ON_STARTUP"
TVENDOR_SESSION_SECRET = "TVENDOR_SESSION_SECRET"
TVENDOR_SESSION_HTTPS_ONLY = "TVENDOR_SESSION_HTTPS_ONLY"
TVENDOR_ALLOW_DEFAULT_SESSION_SECRET = "TVENDOR_ALLOW_DEFAULT_SESSION_SECRET"
TVENDOR_PERF_LOG_ENABLED = "TVENDOR_PERF_LOG_ENABLED"
TVENDOR_PERF_RESPONSE_HEADER = "TVENDOR_PERF_RESPONSE_HEADER"
TVENDOR_SLOW_QUERY_MS = "TVENDOR_SLOW_QUERY_MS"
TVENDOR_ERROR_INCLUDE_DETAILS = "TVENDOR_ERROR_INCLUDE_DETAILS"
TVENDOR_REQUEST_ID_HEADER_ENABLED = "TVENDOR_REQUEST_ID_HEADER_ENABLED"
TVENDOR_TRUST_FORWARDED_IDENTITY_HEADERS = "TVENDOR_TRUST_FORWARDED_IDENTITY_HEADERS"
TVENDOR_FORWARDED_GROUP_HEADERS = "TVENDOR_FORWARDED_GROUP_HEADERS"
TVENDOR_ALLOW_TEST_ROLE_OVERRIDE = "TVENDOR_ALLOW_TEST_ROLE_OVERRIDE"
TVENDOR_DEV_ALLOW_ALL_ACCESS = "TVENDOR_DEV_ALLOW_ALL_ACCESS"
TVENDOR_BOOTSTRAP_DIAGNOSTICS_ENABLED = "TVENDOR_BOOTSTRAP_DIAGNOSTICS_ENABLED"
TVENDOR_BOOTSTRAP_DIAGNOSTICS_TOKEN = "TVENDOR_BOOTSTRAP_DIAGNOSTICS_TOKEN"
TVENDOR_CSRF_ENABLED = "TVENDOR_CSRF_ENABLED"
TVENDOR_WRITE_RATE_LIMIT_ENABLED = "TVENDOR_WRITE_RATE_LIMIT_ENABLED"
TVENDOR_WRITE_RATE_LIMIT_WINDOW_SEC = "TVENDOR_WRITE_RATE_LIMIT_WINDOW_SEC"
TVENDOR_WRITE_RATE_LIMIT_MAX_REQUESTS = "TVENDOR_WRITE_RATE_LIMIT_MAX_REQUESTS"
TVENDOR_QUERY_CACHE_ENABLED = "TVENDOR_QUERY_CACHE_ENABLED"
TVENDOR_QUERY_CACHE_TTL_SEC = "TVENDOR_QUERY_CACHE_TTL_SEC"
TVENDOR_QUERY_CACHE_MAX_ENTRIES = "TVENDOR_QUERY_CACHE_MAX_ENTRIES"
TVENDOR_REPO_CACHE_ENABLED = "TVENDOR_REPO_CACHE_ENABLED"
TVENDOR_REPO_CACHE_TTL_SEC = "TVENDOR_REPO_CACHE_TTL_SEC"
TVENDOR_REPO_CACHE_MAX_ENTRIES = "TVENDOR_REPO_CACHE_MAX_ENTRIES"
TVENDOR_SQL_TRACE_ENABLED = "TVENDOR_SQL_TRACE_ENABLED"
TVENDOR_SQL_TRACE_MAX_LEN = "TVENDOR_SQL_TRACE_MAX_LEN"
TVENDOR_SECURITY_HEADERS_ENABLED = "TVENDOR_SECURITY_HEADERS_ENABLED"
TVENDOR_CSP_ENABLED = "TVENDOR_CSP_ENABLED"
TVENDOR_CSP_POLICY = "TVENDOR_CSP_POLICY"
TVENDOR_METRICS_ENABLED = "TVENDOR_METRICS_ENABLED"
TVENDOR_METRICS_PROMETHEUS_ENABLED = "TVENDOR_METRICS_PROMETHEUS_ENABLED"
TVENDOR_METRICS_PROMETHEUS_PATH = "TVENDOR_METRICS_PROMETHEUS_PATH"
TVENDOR_METRICS_ALLOW_UNAUTHENTICATED = "TVENDOR_METRICS_ALLOW_UNAUTHENTICATED"
TVENDOR_METRICS_AUTH_TOKEN = "TVENDOR_METRICS_AUTH_TOKEN"
TVENDOR_STATSD_ENABLED = "TVENDOR_STATSD_ENABLED"
TVENDOR_STATSD_HOST = "TVENDOR_STATSD_HOST"
TVENDOR_STATSD_PORT = "TVENDOR_STATSD_PORT"
TVENDOR_STATSD_PREFIX = "TVENDOR_STATSD_PREFIX"
TVENDOR_ALERTS_ENABLED = "TVENDOR_ALERTS_ENABLED"
TVENDOR_ALERT_WINDOW_SEC = "TVENDOR_ALERT_WINDOW_SEC"
TVENDOR_ALERT_MIN_REQUESTS = "TVENDOR_ALERT_MIN_REQUESTS"
TVENDOR_ALERT_COOLDOWN_SEC = "TVENDOR_ALERT_COOLDOWN_SEC"
TVENDOR_ALERT_REQUEST_P95_MS = "TVENDOR_ALERT_REQUEST_P95_MS"
TVENDOR_ALERT_ERROR_RATE_PCT = "TVENDOR_ALERT_ERROR_RATE_PCT"
TVENDOR_ALERT_DB_AVG_MS = "TVENDOR_ALERT_DB_AVG_MS"
TVENDOR_DB_POOL_ENABLED = "TVENDOR_DB_POOL_ENABLED"
TVENDOR_DB_POOL_MAX_SIZE = "TVENDOR_DB_POOL_MAX_SIZE"
TVENDOR_DB_POOL_ACQUIRE_TIMEOUT_SEC = "TVENDOR_DB_POOL_ACQUIRE_TIMEOUT_SEC"
TVENDOR_DB_POOL_IDLE_TTL_SEC = "TVENDOR_DB_POOL_IDLE_TTL_SEC"
TVENDOR_LOG_LEVEL = "TVENDOR_LOG_LEVEL"
TVENDOR_LOG_JSON = "TVENDOR_LOG_JSON"
TVENDOR_LOG_CAPTURE_ROOT = "TVENDOR_LOG_CAPTURE_ROOT"
TVENDOR_STARTUP_SPLASH_MIN_DELAY_MS = "TVENDOR_STARTUP_SPLASH_MIN_DELAY_MS"
TVENDOR_STARTUP_SPLASH_MAX_DELAY_MS = "TVENDOR_STARTUP_SPLASH_MAX_DELAY_MS"
TVENDOR_LOADING_OVERLAY_MIN_DELAY_MS = "TVENDOR_LOADING_OVERLAY_MIN_DELAY_MS"
TVENDOR_LOADING_OVERLAY_MAX_DELAY_MS = "TVENDOR_LOADING_OVERLAY_MAX_DELAY_MS"
TVENDOR_LOADING_OVERLAY_SHOW_DELAY_MS = "TVENDOR_LOADING_OVERLAY_SHOW_DELAY_MS"
TVENDOR_LOADING_OVERLAY_SLOW_STATUS_MS = "TVENDOR_LOADING_OVERLAY_SLOW_STATUS_MS"
TVENDOR_LOADING_OVERLAY_SAFETY_MS = "TVENDOR_LOADING_OVERLAY_SAFETY_MS"
TVENDOR_LOCAL_DB_AUTO_INIT = "TVENDOR_LOCAL_DB_AUTO_INIT"
TVENDOR_LOCAL_DB_RESET_ON_START = "TVENDOR_LOCAL_DB_RESET_ON_START"
TVENDOR_LOCAL_DB_SEED = "TVENDOR_LOCAL_DB_SEED"
TVENDOR_LOCAL_DB_SEED_PROFILE = "TVENDOR_LOCAL_DB_SEED_PROFILE"
TVENDOR_USAGE_LOG_MIN_INTERVAL_SEC = "TVENDOR_USAGE_LOG_MIN_INTERVAL_SEC"
TVENDOR_USER_DIRECTORY_TOUCH_TTL_SEC = "TVENDOR_USER_DIRECTORY_TOUCH_TTL_SEC"
TVENDOR_DATABRICKS_REPORTS_JSON = "TVENDOR_DATABRICKS_REPORTS_JSON"
TVENDOR_DATABRICKS_REPORTS_ALLOW_EMBED = "TVENDOR_DATABRICKS_REPORTS_ALLOW_EMBED"
TVENDOR_DATABRICKS_REPORTS_ALLOWED_HOSTS = "TVENDOR_DATABRICKS_REPORTS_ALLOWED_HOSTS"

# Databricks auth/connection keys.
DATABRICKS_SERVER_HOSTNAME = "DATABRICKS_SERVER_HOSTNAME"
DATABRICKS_HTTP_PATH = "DATABRICKS_HTTP_PATH"
DATABRICKS_WAREHOUSE_ID = "DATABRICKS_WAREHOUSE_ID"
DATABRICKS_TOKEN = "DATABRICKS_TOKEN"
DATABRICKS_CLIENT_ID = "DATABRICKS_CLIENT_ID"
DATABRICKS_CLIENT_SECRET = "DATABRICKS_CLIENT_SECRET"

# Backward-compatible aliases still accepted by config resolution.
DATABRICKS_SERVER_HOSTNAME_KEYS = (
    DATABRICKS_SERVER_HOSTNAME,
    "DATABRICKS_HOST",
    "DBSQL_SERVER_HOSTNAME",
)
DATABRICKS_HTTP_PATH_KEYS = (
    DATABRICKS_HTTP_PATH,
    "DATABRICKS_SQL_HTTP_PATH",
    "DBSQL_HTTP_PATH",
    "SQL_HTTP_PATH",
)
DATABRICKS_WAREHOUSE_ID_KEYS = (
    DATABRICKS_WAREHOUSE_ID,
    "DATABRICKS_SQL_WAREHOUSE_ID",
    "SQL_WAREHOUSE_ID",
    "DBSQL_WAREHOUSE_ID",
)
DATABRICKS_RESOURCE_WAREHOUSE_KEYS = (
    "sql-warehouse",
    "sql_warehouse",
    "SQL_WAREHOUSE",
    "SQL-WAREHOUSE",
)


def get_env(key: str, default: str = "") -> str:
    return str(os.getenv(key, default) or "").strip()


def get_first_env(keys: Iterable[str], default: str = "") -> str:
    for key in keys:
        value = get_env(key)
        if value:
            return value
    return str(default or "").strip()


def get_env_bool(key: str, *, default: bool = False) -> bool:
    return as_bool(os.getenv(key), default=default)


def get_env_int(
    key: str,
    *,
    default: int,
    min_value: int | None = None,
    max_value: int | None = None,
) -> int:
    return as_int(
        os.getenv(key),
        default=default,
        min_value=min_value,
        max_value=max_value,
    )


def get_env_float(
    key: str,
    *,
    default: float,
    min_value: float | None = None,
    max_value: float | None = None,
) -> float:
    return as_float(
        os.getenv(key),
        default=default,
        min_value=min_value,
        max_value=max_value,
    )
