# Generated by Django 5.2.11 on 2026-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_id", models.CharField(max_length=255, unique=True)),
                ("workflow_name", models.CharField(max_length=255)),
                ("submitted_by", models.CharField(max_length=255)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("action", models.CharField(max_length=100)),
                ("context_json", models.TextField(blank=True, default="{}")),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
