# Generated by Django 5.2.11 on 2026-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demo_id", models.CharField(max_length=128, unique=True)),
                ("demo_name", models.CharField(max_length=255)),
                ("demo_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "demo_outcome",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lifecycle_state", models.CharField(default="draft", max_length=64)),
                (
                    "project_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
