# Generated by Django 5.2.11 on 2026-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "report_run_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("report_type", models.CharField(max_length=32)),
                ("report_name", models.CharField(max_length=255)),
                ("report_format", models.CharField(default="excel", max_length=16)),
                ("status", models.CharField(default="scheduled", max_length=16)),
                ("triggered_by", models.CharField(max_length=255)),
                ("scheduled_time", models.DateTimeField()),
                ("started_time", models.DateTimeField(blank=True, null=True)),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.IntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report_type", "triggered_by"],
                        name="reports_rep_report__f2c923_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_time"],
                        name="reports_rep_status_720b0c_idx",
                    ),
                ],
            },
        ),
    ]
