# Generated by Django 5.2.11 on 2026-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrun",
            name="report_code",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="filters_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="warnings_json",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="report_format",
            field=models.CharField(default="preview", max_length=16),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="report_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="report_type",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="status",
            field=models.CharField(default="queued", max_length=16),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="triggered_by",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="ReportEmailRequestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=36)),
                ("email_to_csv", models.TextField()),
                ("requested_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["run_id", "created_at"],
                        name="reports_rep_run_id_7f2a4a_idx",
                    )
                ],
            },
        ),
    ]
