# Generated by Django 5.2.11 on 2026-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_phase6_reports_contracts"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reportrun",
            name="reports_rep_report__f2c923_idx",
        ),
        migrations.RenameIndex(
            model_name="reportemailrequestrecord",
            new_name="reports_rep_run_id_9ed283_idx",
            old_name="reports_rep_run_id_7f2a4a_idx",
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(
                fields=["report_code", "triggered_by"],
                name="reports_rep_report__47717d_idx",
            ),
        ),
    ]
