INSERT INTO {app_import_job} (
  import_job_id,
  layout_key,
  source_system,
  source_object,
  file_name,
  file_type,
  detected_format,
  parser_config_json,
  row_count,
  status,
  created_count,
  merged_count,
  skipped_count,
  failed_count,
  error_message,
  created_at,
  created_by,
  applied_at,
  applied_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
