command:
  - "python"
  - "main.py"

# Edit only these values per environment:
# - TVENDOR_CATALOG
# - TVENDOR_SCHEMA
# Optional override if your environment does not use app resource binding:
# - DATABRICKS_WAREHOUSE_ID (or DATABRICKS_HTTP_PATH)
env:
  - name: "TVENDOR_ENV"
    value: "prod"
  - name: "TVENDOR_USE_LOCAL_DB"
    value: "false"
  - name: "TVENDOR_LOCKED_MODE"
    value: "false"
  - name: "TVENDOR_CATALOG"
    value: "a1_dlk"
  - name: "TVENDOR_SCHEMA"
    value: "twvendor"
  - name: "TVENDOR_ENFORCE_PROD_SQL_POLICY"
    value: "true"
  - name: "TVENDOR_ALLOWED_WRITE_VERBS"
    value: "INSERT,UPDATE"
  - name: "TVENDOR_LOG_LEVEL"
    value: "INFO"
  - name: "TVENDOR_LOG_JSON"
    value: "false"
  - name: "TVENDOR_LOG_CAPTURE_ROOT"
    value: "false"
  - name: "TVENDOR_PERF_LOG_ENABLED"
    value: "true"
  - name: "TVENDOR_PERF_RESPONSE_HEADER"
    value: "true"
  - name: "TVENDOR_SQL_TRACE_ENABLED"
    value: "true"
  - name: "TVENDOR_SLOW_QUERY_MS"
    value: "250"
  - name: "TVENDOR_SQL_TRACE_MAX_LEN"
    value: "220"
  - name: "TVENDOR_USAGE_LOG_ENABLED"
    value: "false"
  - name: "TVENDOR_USAGE_LOG_MIN_INTERVAL_SEC"
    value: "300"
  - name: "TVENDOR_USER_DIRECTORY_TOUCH_TTL_SEC"
    value: "900"
  - name: "TVENDOR_IDENTITY_SYNC_TTL_SEC"
    value: "1800"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
