command:
  - "python"
  - "main.py"

# Edit only these values per environment:
# - TVENDOR_CATALOG
# - TVENDOR_SCHEMA
# Optional if your runtime does not auto-populate SQL path:
# - DATABRICKS_WAREHOUSE_ID (or DATABRICKS_HTTP_PATH)
env:
  - name: "TVENDOR_ENV"
    value: "prod"
  - name: "TVENDOR_USE_LOCAL_DB"
    value: "false"
  - name: "TVENDOR_LOCKED_MODE"
    value: "false"
  - name: "TVENDOR_CATALOG"
    value: "a1_dlk"
  - name: "TVENDOR_SCHEMA"
    value: "twanalytics"
  - name: "TVENDOR_ENFORCE_PROD_SQL_POLICY"
    value: "true"
  - name: "TVENDOR_ALLOWED_WRITE_VERBS"
    value: "INSERT,UPDATE"
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: ""
