@echo off
setlocal

cd /d "%~dp0"
set "TVENDOR_ENV_FILE=setup\config\tvendor.dev_pat.env"
set "TVENDOR_ENV_FORCE=true"
set "TVENDOR_ENV=dev"
set "TVENDOR_USE_LOCAL_DB=true"
set "TVENDOR_LOCAL_DB_SEED=true"
set "TVENDOR_LOCAL_DB_SEED_PROFILE=full"
set "TVENDOR_LOCAL_DB_REBUILD_MODE=keep"
set "TVENDOR_DEV_ALLOW_ALL_ACCESS=true"
if "%TVENDOR_TEST_USER%"=="" set "TVENDOR_TEST_USER=dev_admin@example.com"
echo Dev launcher forcing local DB + full access mode:
echo   TVENDOR_USE_LOCAL_DB=%TVENDOR_USE_LOCAL_DB%
echo   TVENDOR_LOCAL_DB_SEED=%TVENDOR_LOCAL_DB_SEED%
echo   TVENDOR_LOCAL_DB_SEED_PROFILE=%TVENDOR_LOCAL_DB_SEED_PROFILE%
echo   TVENDOR_LOCAL_DB_REBUILD_MODE=%TVENDOR_LOCAL_DB_REBUILD_MODE%
echo   TVENDOR_DEV_ALLOW_ALL_ACCESS=%TVENDOR_DEV_ALLOW_ALL_ACCESS%
echo   TVENDOR_TEST_USER=%TVENDOR_TEST_USER%
call launch_app.bat

endlocal
