# Generated by Django 5.2.11 on 2026-02-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offering_id", models.CharField(max_length=128, unique=True)),
                ("offering_name", models.CharField(max_length=255)),
                (
                    "offering_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("lob", models.CharField(blank=True, default="", max_length=128)),
                (
                    "service_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("lifecycle_state", models.CharField(default="draft", max_length=64)),
                (
                    "criticality_tier",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
    ]
