# Generated by Django 5.2.11 on 2026-02-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0002_offering_nested_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferingProgramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internal_owner", models.CharField(blank=True, default="", max_length=255)),
                ("vendor_success_manager", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sla_target_pct",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("rto_hours", models.IntegerField(blank=True, null=True)),
                ("data_residency", models.CharField(blank=True, default="", max_length=128)),
                ("compliance_tags", models.CharField(blank=True, default="", max_length=512)),
                (
                    "budget_annual",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("roadmap_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offering",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_profile",
                        to="offerings.offering",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferingEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entitlement_name", models.CharField(max_length=255)),
                ("license_type", models.CharField(blank=True, default="", max_length=128)),
                ("purchased_units", models.IntegerField(default=0)),
                ("assigned_units", models.IntegerField(default=0)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("true_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="offerings.offering",
                    ),
                ),
            ],
        ),
    ]
