# Generated by Django 5.2.11 on 2026-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_job_id", models.CharField(max_length=255, unique=True)),
                ("source_system", models.CharField(max_length=100)),
                (
                    "source_object",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("status", models.CharField(default="submitted", max_length=50)),
                ("submitted_by", models.CharField(max_length=255)),
                (
                    "mapping_profile_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("staged_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MappingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_id", models.CharField(max_length=255, unique=True)),
                ("profile_name", models.CharField(max_length=255)),
                ("layout_key", models.CharField(default="vendors", max_length=100)),
                ("file_format", models.CharField(max_length=50)),
                ("source_fields_json", models.TextField(blank=True, default="[]")),
                (
                    "source_target_mapping_json",
                    models.TextField(blank=True, default="{}"),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
