# Generated by Django 5.2.11 on 2026-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="importjob",
            name="workflow_context_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
