# Generated by Django 5.2.11 on 2026-02-21 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["display_name"]},
        ),
        migrations.AlterModelTable(
            name="vendor",
            table="core_vendor",
        ),
        migrations.CreateModel(
            name="VendorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Contact"),
                            ("sales", "Sales Representative"),
                            ("support", "Support Contact"),
                            ("billing", "Billing Contact"),
                            ("technical", "Technical Contact"),
                            ("executive", "Executive"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_contact",
                "ordering": ["-is_primary", "full_name"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"],
                        name="core_vendor_vendor__5ed4a5_idx",
                    ),
                    models.Index(
                        fields=["vendor", "contact_type"],
                        name="core_vendor_vendor__d4f4b5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("duns", "DUNS Number"),
                            ("tax_id", "Tax ID / EIN"),
                            ("vat_id", "VAT ID"),
                            ("gln", "GLN (Global Location Number)"),
                            ("erp_id", "ERP Vendor ID"),
                            ("sap_id", "SAP Vendor Code"),
                            ("internal_id", "Internal ID"),
                            ("d_u_n_s_plus_4", "DUNS+4"),
                            ("cage_code", "CAGE Code"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("identifier_value", models.CharField(max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_identifier",
                "ordering": ["-is_primary", "identifier_type"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "identifier_type"],
                        name="core_vendor_vendor__cebad1_idx",
                    ),
                    models.Index(
                        fields=["identifier_type", "identifier_value"],
                        name="core_vendor_identif_e57f49_idx",
                    ),
                ],
                "unique_together": {("vendor", "identifier_type", "identifier_value")},
            },
        ),
    ]
