# Generated by Django 5.2.11 on 2026-02-21 02:50

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_add_vendor_contacts_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_information", "Pending Information"),
                            ("under_review", "Under Review"),
                            ("compliance_check", "Compliance Check"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_column="onboarding_state",
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "initiated_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_state_change", models.DateTimeField(auto_now=True)),
                (
                    "status_change_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("initial_creation", "Initial Creation"),
                            ("missing_documents", "Missing Required Documents"),
                            ("compliance_issue", "Compliance Issue"),
                            ("risk_assessment", "Risk Assessment"),
                            ("manager_approval", "Manager Approval"),
                            ("rejected_applicant", "Rejected by Applicant"),
                            ("rejected_internal", "Rejected Internally"),
                            ("onboarding_complete", "Onboarding Complete"),
                            ("policy_change", "Policy Change"),
                            ("other", "Other Reason"),
                        ],
                        default="initial_creation",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("status_change_notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_reviewer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("assigned_date", models.DateTimeField(blank=True, null=True)),
                ("review_completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "information_request_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("documents_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compliance_check_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_workflow",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_onboarding_workflow",
                "ordering": ["-initiated_at"],
            },
        ),
    ]
