# Generated by Django 5.2.11 on 2026-02-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_add_onboarding_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.CharField(max_length=128)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("signed", "Signed"),
                            ("activated", "Activated"),
                            ("renewed", "Renewed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=64,
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("actor_user_principal", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_contract_event",
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["contract_id"], name="core_contra_contrac_07b540_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfferingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offering_id", models.CharField(max_length=128)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("performance", "Performance"),
                            ("issue", "Issue"),
                        ],
                        max_length=64,
                    ),
                ),
                ("note_text", models.TextField()),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_offering_note",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["offering_id"], name="core_offeri_offerin_0c1ebc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfferingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offering_id", models.CharField(max_length=128)),
                (
                    "ticket_system",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "external_ticket_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=64,
                    ),
                ),
                ("opened_date", models.DateTimeField()),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_offering_ticket",
                "ordering": ["-opened_date"],
                "indexes": [
                    models.Index(
                        fields=["offering_id"], name="core_offeri_offerin_be97d1_idx"
                    )
                ],
                "unique_together": {
                    ("offering_id", "ticket_system", "external_ticket_id")
                },
            },
        ),
        migrations.CreateModel(
            name="VendorDemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offering_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("demo_id", models.CharField(max_length=128, unique=True)),
                ("demo_date", models.DateTimeField()),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "selection_outcome",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("not_selected", "Not Selected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "attendees_internal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attendees_vendor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_demos",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_demo",
                "ordering": ["-demo_date"],
            },
        ),
        migrations.CreateModel(
            name="DemoScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_category", models.CharField(max_length=128)),
                ("score_value", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="vendors.vendordemo",
                    ),
                ),
            ],
            options={
                "db_table": "core_demo_score",
                "ordering": ["score_category"],
            },
        ),
        migrations.CreateModel(
            name="DemoNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("observation", "Observation"),
                            ("issue", "Issue"),
                            ("strength", "Strength"),
                        ],
                        max_length=64,
                    ),
                ),
                ("note_text", models.TextField()),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_notes",
                        to="vendors.vendordemo",
                    ),
                ),
            ],
            options={
                "db_table": "core_demo_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("risk", "Risk"),
                            ("compliance", "Compliance"),
                            ("performance", "Performance"),
                            ("issue", "Issue"),
                        ],
                        max_length=64,
                    ),
                ),
                ("note_text", models.TextField()),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_notes",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorOrgAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=128)),
                ("org_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("assigned_by", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_assignments",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_org_assignment",
                "ordering": ["-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="VendorTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_system",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "external_ticket_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=64,
                    ),
                ),
                ("opened_date", models.DateTimeField()),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_tickets",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_ticket",
                "ordering": ["-opened_date"],
            },
        ),
        migrations.CreateModel(
            name="VendorWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warning_category", models.CharField(max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, null=True)),
                ("detected_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_warnings",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_warning",
                "ordering": ["-severity", "-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorBusinessOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_user_principal", models.CharField(max_length=255)),
                ("owner_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner_department",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("assigned_by", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_owners",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "core_vendor_business_owner",
                "ordering": ["-is_primary"],
                "unique_together": {("vendor", "owner_user_principal")},
            },
        ),
        migrations.AddIndex(
            model_name="vendordemo",
            index=models.Index(
                fields=["vendor"], name="core_vendor_vendor__3c53e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornote",
            index=models.Index(
                fields=["vendor"], name="core_vendor_vendor__71fc78_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendororgassignment",
            unique_together={("vendor", "org_id")},
        ),
        migrations.AddIndex(
            model_name="vendorticket",
            index=models.Index(
                fields=["vendor", "status"], name="core_vendor_vendor__eaa291_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorticket",
            unique_together={("vendor", "ticket_system", "external_ticket_id")},
        ),
        migrations.AddIndex(
            model_name="vendorwarning",
            index=models.Index(
                fields=["vendor", "status"], name="core_vendor_vendor__5a5c67_idx"
            ),
        ),
    ]
