# Generated by Django 5.2.11 on 2026-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "article_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("article_title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=32)),
                ("content_markdown", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("author", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="help_center_categor_7b7c40_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="help_center_created_95466d_idx"
                    ),
                ],
            },
        ),
    ]
