# Generated by Django 5.2.11 on 2026-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_center", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helparticle",
            name="slug",
            field=models.SlugField(default="", max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="markdown_body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="rendered_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="helparticle",
            name="article_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="helparticle",
            name="content_markdown",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="HelpFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=128)),
                ("rating", models.CharField(max_length=8)),
                ("comment", models.TextField(blank=True, default="")),
                ("submitted_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["slug", "created_at"],
                        name="help_center_slug_f06f6e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=128)),
                ("issue_text", models.TextField()),
                ("screenshot_path", models.CharField(blank=True, default="", max_length=512)),
                ("submitted_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["slug", "created_at"],
                        name="help_center_slug_7600e8_idx",
                    )
                ],
            },
        ),
    ]
