# Generated by Django 5.2.11 on 2026-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_center", "0002_phase6_help_contracts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="helpfeedback",
            new_name="help_center_slug_9b5593_idx",
            old_name="help_center_slug_f06f6e_idx",
        ),
        migrations.RenameIndex(
            model_name="helpissue",
            new_name="help_center_slug_5bab48_idx",
            old_name="help_center_slug_7600e8_idx",
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["slug", "published"], name="help_center_slug_9b3a43_idx"
            ),
        ),
    ]
